language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
before_deploy:
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: storybook-static
  on:
    branch: master
branches:
  only:
  - master
